# Site Settings
title: Top
tagline: top page
email: your-email@domain.com
description: >
  分子科学研究所　南谷グループ　Webサイト（工事中）
baseurl: "/website-under-construction"
#not sure 0.7.2 is necessary or not
#remote_theme: chrisrhymes/bulma-clean-theme@0.7.2
remote_theme: chrisrhymes/bulma-clean-theme
url: "https://eminamitani.github.io/website-under-construction"
permalink: pretty
#locale: ja_JP
#favicon: /path/to/favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: eminamitani


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - github-pages

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Emi Minamitani"
      layout: post
      image: 
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false